Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,4 +29,10 @@ jobs:
       run: dotnet pack Maui.LocalDB.Sync/Maui.LocalDB.Sync/Maui.LocalDB.Sync.csproj --configuration Release -o out
 
     - name: Publish to NuGet
-      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+      run: |
+        FILE=$(ls out/*.nupkg | head -n 1)
+        if [ -z "$FILE" ]; then
+          echo "No package file found in ./out. Check the pack step for errors."
+          exit 1
+        fi
+        dotnet nuget push "$FILE" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
